#! /bin/sh
# Script to shut down a network (tap) device for qemu.
# Initially this script is empty, but you can configure,
# for example, accounting info here.


echo "Executing qemu-ifdown"
sudo ip link set $1 down
sudo ip link delete dev $1
