#!/usr/bin/env python3

import subprocess
import time
import os

# Start xv6
proc = subprocess.Popen(
    ["make", "qemu"],
    stdin=subprocess.PIPE,
    stdout=subprocess.PIPE,
    stderr=subprocess.STDOUT
)

def send(cmd):
    proc.stdin.write((cmd + "\n").encode())
    proc.stdin.flush()

def read_output(seconds=2):
    time.sleep(seconds)
    try:
        output = os.read(proc.stdout.fileno(), 4096).decode()
        print(output)
    except:
        pass

# wait for xv6 to boot
time.sleep(2)

print("Running getppid...")
send("test_getppid")
read_output()

print("Running sleep2...")
send("test_sleep2")
read_output(3)

print("Running procs...")
send("test_procs")
read_output()

# stop xv6
proc.terminate()
