name: Run XV6 in QEMU

on: [push, pull_request]

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential qemu-system-misc gcc-riscv64-linux-gnu binutils-riscv64-linux-gnu expect

      - name: Run make qemu in Expect
        run: |
          # QEMU runs indefinitely unless terminated. We use expect to start it, wait briefly, and send exit commands.
          expect -c '
            spawn make qemu
            expect "init: starting sh"
            sleep 2
            send "\x01"
            send "x"
            expect eof
          '
