on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/checkout@v7
      - run: sudo apt-get update && sudo apt-get install -y gcc-riscv64-linux-gnu qemu-system-riscv clang-format bc
      - run: make fmt && git diff --exit-code
      - run: make kernel/kernel fs.img
      - run: ./test-xv6.py usertests
      - run: ./test-xv6.py crash

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v7
      - run: brew install riscv64-elf-gcc
      - run: make kernel/kernel fs.img
